"""Pathwise symbolic topological dynamics for the V5.1 hybrid state space."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


SURFACE_COUNT = 4
SYMBOL_COUNT = 1 << SURFACE_COUNT


@dataclass(frozen=True)
class TopologicalFactors:
    command: np.ndarray
    financial: np.ndarray
    logistics: np.ndarray
    mobilization: np.ndarray
    panic_impulse: np.ndarray
    instability: np.ndarray
    recurrence: np.ndarray
    symbol: np.ndarray


class TopologicalRegimeDynamics:
    """Online symbolic dynamics with a finite Morse-graph approximation.

    Each actor/path occupies one of 16 cells generated by the four Filippov
    regime indicators.  Transitions remain pathwise; cross-path aggregation is
    used only for diagnostics after simulation.
    """

    def __init__(self, paths: int) -> None:
        self.paths = paths
        self.previous_symbol = np.zeros((paths, 4), dtype=np.uint8)
        self.initialized = False
        self.transition_counts = np.zeros(
            (paths, 4, SYMBOL_COUNT, SYMBOL_COUNT), dtype=np.uint16
        )
        self.visit_counts = np.zeros((paths, 4, SYMBOL_COUNT), dtype=np.uint16)
        self.months = 0
        self.max_probability_residual = 0.0
        self.max_feedback_deviation = 0.0

    @staticmethod
    def _encode(regime: np.ndarray) -> np.ndarray:
        weights = (1 << np.arange(SURFACE_COUNT, dtype=np.uint8))[None, None, :]
        return np.sum(regime.astype(np.uint8) * weights, axis=2).astype(np.uint8)

    @staticmethod
    def _popcount(values: np.ndarray) -> np.ndarray:
        result = np.zeros_like(values, dtype=float)
        for bit in range(SURFACE_COUNT):
            result += ((values >> bit) & 1).astype(float)
        return result

    def update(
        self,
        regime: np.ndarray,
        conflict_regime: np.ndarray,
        collapse: np.ndarray,
    ) -> TopologicalFactors:
        symbol = self._encode(regime)
        path = np.arange(self.paths)[:, None]
        actor = np.arange(4)[None, :]
        prior_visits = self.visit_counts[path, actor, symbol].astype(float)
        if self.initialized:
            previous = self.previous_symbol.copy()
            prior_edge = self.transition_counts[path, actor, previous, symbol].astype(float)
            outgoing = np.sum(
                self.transition_counts[path, actor, previous, :], axis=2
            ).astype(float)
            recurrence = prior_edge / np.maximum(outgoing, 1.0)
            novelty = (prior_edge == 0.0).astype(float)
            hamming = self._popcount(np.bitwise_xor(previous, symbol)) / SURFACE_COUNT
            current = self.transition_counts[path, actor, previous, symbol]
            self.transition_counts[path, actor, previous, symbol] = np.minimum(
                current.astype(np.uint32) + 1, np.iinfo(np.uint16).max
            ).astype(np.uint16)
        else:
            recurrence = np.zeros((self.paths, 4))
            novelty = np.zeros((self.paths, 4))
            hamming = np.zeros((self.paths, 4))
            self.initialized = True
        current_visits = self.visit_counts[path, actor, symbol]
        self.visit_counts[path, actor, symbol] = np.minimum(
            current_visits.astype(np.uint32) + 1, np.iinfo(np.uint16).max
        ).astype(np.uint16)
        residence = prior_visits / max(self.months + 1, 1)
        conflict = np.broadcast_to((conflict_regime != 5)[:, None], (self.paths, 4))
        collapse_signal = np.mean(collapse.astype(float), axis=2)
        instability = np.clip(
            (0.50 * hamming + 0.24 * novelty + 0.16 * (1.0 - recurrence)
             + 0.06 * conflict + 0.04 * collapse_signal)
            * np.where(self.months == 0, 0.0, 1.0),
            0.0, 1.0,
        )
        stability = np.clip(0.62 * recurrence + 0.38 * residence, 0.0, 1.0)
        command = np.clip(1.0 - 0.055 * instability + 0.012 * stability, 0.90, 1.02)
        financial = np.clip(1.0 - 0.040 * instability + 0.010 * stability, 0.92, 1.02)
        logistics = np.clip(1.0 - 0.035 * instability + 0.008 * stability, 0.93, 1.02)
        mobilization = np.clip(1.0 + 0.025 * instability - 0.008 * stability, 0.98, 1.04)
        panic_impulse = np.clip(0.008 * instability - 0.002 * stability, -0.002, 0.008)
        self.max_feedback_deviation = max(
            self.max_feedback_deviation,
            float(np.max(np.abs(command - 1.0))),
            float(np.max(np.abs(financial - 1.0))),
            float(np.max(np.abs(logistics - 1.0))),
            float(np.max(np.abs(mobilization - 1.0))),
        )
        self.previous_symbol = symbol
        self.months += 1
        return TopologicalFactors(
            command=command, financial=financial, logistics=logistics,
            mobilization=mobilization, panic_impulse=panic_impulse,
            instability=instability, recurrence=recurrence, symbol=symbol,
        )

    @staticmethod
    def _strongly_connected_components(adjacency: np.ndarray) -> list[list[int]]:
        index = 0
        stack: list[int] = []
        on_stack = set()
        indices = [-1] * len(adjacency)
        lowlink = [0] * len(adjacency)
        components: list[list[int]] = []

        def visit(node: int) -> None:
            nonlocal index
            indices[node] = index
            lowlink[node] = index
            index += 1
            stack.append(node)
            on_stack.add(node)
            for target in np.flatnonzero(adjacency[node]):
                target = int(target)
                if indices[target] < 0:
                    visit(target)
                    lowlink[node] = min(lowlink[node], lowlink[target])
                elif target in on_stack:
                    lowlink[node] = min(lowlink[node], indices[target])
            if lowlink[node] == indices[node]:
                component = []
                while True:
                    target = stack.pop()
                    on_stack.remove(target)
                    component.append(target)
                    if target == node:
                        break
                components.append(sorted(component))

        for node in range(len(adjacency)):
            if indices[node] < 0:
                visit(node)
        return components

    def diagnostics(self) -> dict:
        aggregate = np.sum(self.transition_counts.astype(np.uint64), axis=(0, 1))
        adjacency = aggregate > 0
        components = self._strongly_connected_components(adjacency)
        component_of = {}
        for component_index, component in enumerate(components):
            for node in component:
                component_of[node] = component_index
        outgoing = [set() for _ in components]
        for source, target in zip(*np.nonzero(adjacency)):
            left, right = component_of[int(source)], component_of[int(target)]
            if left != right:
                outgoing[left].add(right)
        recurrent = [
            components[i] for i, targets in enumerate(outgoing) if not targets
        ]
        eigenvalues = np.linalg.eigvals(adjacency.astype(float))
        spectral_radius = float(np.max(np.abs(eigenvalues))) if eigenvalues.size else 0.0
        expected = self.paths * 4 * max(self.months - 1, 0)
        actual = int(np.sum(aggregate))
        visited = np.sum(self.visit_counts.astype(np.uint64), axis=(0, 1))
        return {
            "symbol_count": SYMBOL_COUNT,
            "months": self.months,
            "transition_accounting_residual": abs(actual - expected),
            "observed_transition_edges": int(np.count_nonzero(adjacency)),
            "visited_symbols": np.flatnonzero(visited).astype(int).tolist(),
            "morse_sets": components,
            "recurrent_morse_sets": recurrent,
            "morse_condensation_edges": int(sum(len(targets) for targets in outgoing)),
            "topological_entropy_upper_proxy": float(np.log(max(spectral_radius, 1.0))),
            "max_feedback_deviation": self.max_feedback_deviation,
            "max_probability_residual": self.max_probability_residual,
        }
